// Auto-generated by @cxxgo/genapi@1.1.4

import Mock from 'better-mock'
import { ApiResponseShuJuYiZhiXingCaoZuoFanHuiJieGuo } from './_interfaces'

/** 根据流水号出行结果 */
export const dataSyncCheckResult = () => Mock.mock(ApiResponseShuJuYiZhiXingCaoZuoFanHuiJieGuo())
