// Auto-generated by @cxxgo/genapi@1.1.4

import Mock from 'better-mock'
import { ApiResponseListstring } from './_interfaces'

/** 出行菜谱 */
export const dictQueryType = () => Mock.mock(ApiResponseListstring())
