// Auto-generated by @cxxgo/genapi@2.0.2-alpha.0

import Mock from 'better-mock'
import { ApiResponseListstring } from './_interfaces'

/** 出行菜谱 */
export const dictQueryType = () => Mock.mock(ApiResponseListstring())
