// Auto-generated by @cxxgo/genapi@2.0.2-alpha.0

import Mock from 'better-mock'
import { ApiResponseListWenJianShangChuanXiangYing } from './_interfaces'

/** 文件上传 */
export const fileUpload = () => Mock.mock(ApiResponseListWenJianShangChuanXiangYing())
