// Auto-generated by @cxxgo/genapi@1.1.4

import Mock from 'better-mock'
import { ApiResponseListWenJianShangChuanXiangYing } from './_interfaces'

/** 文件上传 */
export const fileUpload = () => Mock.mock(ApiResponseListWenJianShangChuanXiangYing())
