// Auto-generated by @cxxgo/genapi@2.0.0

import Mock from 'better-mock'
import { ApiResponseboolean, ApiResponseZhiXieChangFangDongXinXiXiangQing } from './_interfaces'

/** 获取制鞋厂房东信息详情 */
export const gratefulDoorAcquireInfo = () => Mock.mock(ApiResponseZhiXieChangFangDongXinXiXiangQing())

/** 修改制鞋厂房东信息 */
export const gratefulDoorUpdateInfo = () => Mock.mock(ApiResponseboolean())
