// Auto-generated by @cxxgo/genapi@2.0.2-alpha.0

import Mock from 'better-mock'
import { ApiResponseboolean, ApiResponseDouJiangJiFangDongXinXiXiangQingBiao } from './_interfaces'

/** 获取豆浆机房东信息详情 */
export const gratefulCatAcquireInfo = () => Mock.mock(ApiResponseDouJiangJiFangDongXinXiXiangQingBiao())

/** 修改密码 */
export const gratefulCatUpdateAccPassword = () => Mock.mock(ApiResponseboolean())

/** 修改房东豆浆机信息 */
export const gratefulCatUpdateInfo = () => Mock.mock(ApiResponseboolean())
