// Auto-generated by @cxxgo/genapi@2.0.0

import Mock from 'better-mock'
import { ApiResponseComPageLogLoginResp } from './_interfaces'

/** 登录日志 */
export const logList = () => Mock.mock(ApiResponseComPageLogLoginResp())
