// Auto-generated by @cxxgo/genapi@1.1.4

import Mock from 'better-mock'
import { ApiResponseComPageLogLoginResp } from './_interfaces'

/** 登录日志 */
export const logList = () => Mock.mock(ApiResponseComPageLogLoginResp())
