// Auto-generated by @cxxgo/genapi@2.0.0

import Mock from 'better-mock'
import { ApiResponse, ApiResponseListSuperManResp, ApiResponsestring } from './_interfaces'

/** 甬道 */
export const superList = () => Mock.mock(ApiResponseListSuperManResp())

/** 转让 */
export const superTransfer = () => Mock.mock(ApiResponse())

/** 转让验山麻杆码验山麻杆 */
export const superVerifyVerifyType = () => Mock.mock(ApiResponsestring())
