// Auto-generated by @cxxgo/genapi@2.0.2-alpha.0

import Mock from 'better-mock'
import { ApiResponseNiaoWoWenJianShangChuanXiangYingShiTi } from './_interfaces'

/** 上传鸟窝文件 */
export const birdFileSave = () => Mock.mock(ApiResponseNiaoWoWenJianShangChuanXiangYingShiTi())
