// Auto-generated by @cxxgo/genapi@1.1.4

import Mock from 'better-mock'
import { ApiResponseNiaoWoWenJianShangChuanXiangYingShiTi } from './_interfaces'

/** 上传鸟窝文件 */
export const birdFileSave = () => Mock.mock(ApiResponseNiaoWoWenJianShangChuanXiangYingShiTi())
