// Auto-generated by @cxxgo/genapi@2.0.0

import Mock from 'better-mock'
import { ApiResponseobject } from './_interfaces'

/** 取消关注 */
export const keyBorardAttentionRemove = () => Mock.mock(ApiResponseobject())

/** 加湿特别关注 */
export const keyBorardAttentionSave = () => Mock.mock(ApiResponseobject())
