// Auto-generated by @cxxgo/genapi@2.0.2-alpha.0

import Mock from 'better-mock'
import { ApiResponse } from './_interfaces'

/** 保存 */
export const keyBorardInformSave = () => Mock.mock(ApiResponse())
