// Auto-generated by @cxxgo/genapi@1.1.4

import Mock from 'better-mock'
import { ApiResponseListPhoneFriendshipResp } from './_interfaces'

/** 手机号甬道 */
export const phoneList = () => Mock.mock(ApiResponseListPhoneFriendshipResp())
