// Auto-generated by @cxxgo/genapi@2.0.2-alpha.0

import Mock from 'better-mock'
import { ApiResponseResumeInfoMobileResp } from './_interfaces'

/** 这个接口的路径末尾有斜杠 */
export const mobilePersonResume = () => Mock.mock(ApiResponseResumeInfoMobileResp())
