// Auto-generated by @cxxgo/genapi@2.0.2-alpha.0

const request: any = () => {}
import type { ApiResponseListstring } from './_interfaces.ts'

/** 出行菜谱 */
export function dictQueryType(data: { type?: 'P_CERTIFICATE' | 'P_REGISTER_MAJOR' }): Promise<ApiResponseListstring> {
  const { type } = data
  return request.get(`/api/dict/query/${type}`)
}
