// Auto-generated by @cxxgo/genapi@1.1.4

const request: any = () => {}
import type { ApiResponseboolean, ApiResponseQueryWalletBalanceResp } from './_interfaces.ts'

/** 出行余额 */
export function walletBalance(data: { doorID?: string }): Promise<ApiResponseQueryWalletBalanceResp> {
  return request.get('/api/wallet/balance', data)
}

/** 是否开通 */
export function walletJudgeStatus(): Promise<ApiResponseboolean> {
  return request.get('/api/wallet/judgeStatus')
}
