// Auto-generated by @cxxgo/genapi@1.1.4

import Mock from 'better-mock'
import { ApiResponseMemberBirdStatusResp } from './_interfaces'

/** 本部落状态 */
export const birdStatus = () => Mock.mock(ApiResponseMemberBirdStatusResp())
