// Auto-generated by @cxxgo/genapi@2.0.2-alpha.0

import Mock from 'better-mock'
import {
  ApiResponseComPageCommonSearchResp,
  ApiResponseComPageSearchBeforeAddFriendResp,
  ApiResponseKeyBorardBindResp,
  ApiResponseListSwitchKeyBorardListResp,
  ApiResponseMapstringSearchMapResp,
} from './_interfaces'

/** 结盟设备 */
export const commonBind = () => Mock.mock(ApiResponseKeyBorardBindResp())

/** 结盟设备 */
export const commonBind = () => Mock.mock(ApiResponseKeyBorardBindResp())

/** 聚合搜索 */
export const commonSearch = () => Mock.mock(ApiResponseMapstringSearchMapResp())

/** 聚合搜索 */
export const commonSearch = () => Mock.mock(ApiResponseMapstringSearchMapResp())

/** 搜索人员添加好友前 */
export const commonSearchBeforeAddFriend = () => Mock.mock(ApiResponseComPageSearchBeforeAddFriendResp())

/** 搜索人员添加好友前 */
export const commonSearchBeforeAddFriend = () => Mock.mock(ApiResponseComPageSearchBeforeAddFriendResp())

/** 按照类型搜索 */
export const commonSearchType = () => Mock.mock(ApiResponseComPageCommonSearchResp())

/** 按照类型搜索 */
export const commonSearchType = () => Mock.mock(ApiResponseComPageCommonSearchResp())

/** 结盟设备 */
export const commonSwitchChannel = () => Mock.mock(ApiResponseKeyBorardBindResp())

/** 结盟设备 */
export const commonSwitchChannel = () => Mock.mock(ApiResponseKeyBorardBindResp())

/** 切换铜钱草时铜钱草秋千 */
export const commonSwitchKeyBorardList = () => Mock.mock(ApiResponseListSwitchKeyBorardListResp())

/** 切换铜钱草时铜钱草秋千 */
export const commonSwitchKeyBorardList = () => Mock.mock(ApiResponseListSwitchKeyBorardListResp())
