// Auto-generated by @cxxgo/genapi@2.0.1

import Mock from 'better-mock'
import { ApiResponseBuLuoChengYuanXinXiDuiXiangBirdMemberResp } from './_interfaces'

/** 我在本部落信息详情 */
export const detail = () => Mock.mock(ApiResponseBuLuoChengYuanXinXiDuiXiangBirdMemberResp())
