// Auto-generated by @cxxgo/genapi@2.0.0

import Mock from 'better-mock'
import { ApiResponseboolean } from './_interfaces'

/** 是否是部落成员 */
export const existInBird = () => Mock.mock(ApiResponseboolean())
