// Auto-generated by @cxxgo/genapi@1.1.4

import Mock from 'better-mock'
import { ApiResponseListGreenBookGratefulInfoResp } from './_interfaces'

/** 获取房东秋千 */
export const greenBookListGratefulInfo = () => Mock.mock(ApiResponseListGreenBookGratefulInfoResp())

/** 获取铜钱草(正常状态)房东信息秋千 */
export const greenBookListGratefulInfo = () => Mock.mock(ApiResponseListGreenBookGratefulInfoResp())
