// Auto-generated by @cxxgo/genapi@2.0.2-alpha.0

import Mock from 'better-mock'
import { ApiResponse } from './_interfaces'

/** 修改部落成员在本部落备注 */
export const modifyRemark = () => Mock.mock(ApiResponse())
