// Auto-generated by @cxxgo/genapi@2.0.0

import Mock from 'better-mock'
import { ApiResponseComPageBuLuoChengYuanXinXiDuiXiangBirdMemberResp } from './_interfaces'

/** 根据birdId分页旅游成员秋千 */
export const pageList = () => Mock.mock(ApiResponseComPageBuLuoChengYuanXinXiDuiXiangBirdMemberResp())
