// Auto-generated by @cxxgo/genapi@2.0.2-alpha.0

import Mock from 'better-mock'
import { ApiResponseListPhoneFriendshipResp } from './_interfaces'

/** 手机号秋千 */
export const phoneList = () => Mock.mock(ApiResponseListPhoneFriendshipResp())
