// Auto-generated by @cxxgo/genapi@2.0.2-alpha.0

import Mock from 'better-mock'
import { ApiResponse } from './_interfaces'

/** 请求回复消息保存 */
export const requestMsgSave = () => Mock.mock(ApiResponse())
