// Auto-generated by @cxxgo/genapi@2.0.0

import Mock from 'better-mock'

/** 添加token到缓存 */
export const tokenAddTokenToShangyunCache = () => Mock.mock('')

/** 校验token */
export const tokenCheckToken = () => Mock.mock('@boolean')

/** 倒垃圾session */
export const tokenRemoveSessionInShangyun = () => Mock.mock('')
