// Auto-generated by @cxxgo/genapi@2.0.0

import Mock from 'better-mock'
import {
  ApiResponseComPageDaDuNanTongQianCaoQiuQianWhiteKeyBorardResp,
  ApiResponseListDaDuNanXinXiWhiteResp,
  ApiResponseListKeyBorardListAllGratefulResp,
} from './_interfaces'

/** 获取当前铜钱草所有房东好看人 */
export const whiteKeyBorardListAllGrateful = () => Mock.mock(ApiResponseListKeyBorardListAllGratefulResp())

/** 获取当前铜钱草所有房东好看人 */
export const whiteKeyBorardListAllGrateful = () => Mock.mock(ApiResponseListKeyBorardListAllGratefulResp())

/** 分页获取大肚腩下好看铜钱草秋千 */
export const whiteKeyBorardPage = () => Mock.mock(ApiResponseComPageDaDuNanTongQianCaoQiuQianWhiteKeyBorardResp())

/** 分页获取大肚腩下好看铜钱草秋千 */
export const whiteKeyBorardPage = () => Mock.mock(ApiResponseComPageDaDuNanTongQianCaoQiuQianWhiteKeyBorardResp())

/** 获取铜钱草好看大肚腩秋千 */
export const whiteKeyBorardWhiteList = () => Mock.mock(ApiResponseListDaDuNanXinXiWhiteResp())

/** 获取铜钱草好看大肚腩秋千 */
export const whiteKeyBorardWhiteList = () => Mock.mock(ApiResponseListDaDuNanXinXiWhiteResp())

/** 获取子大肚腩秋千+团建架构imgrouid */
export const whiteList = () => Mock.mock(ApiResponseListDaDuNanXinXiWhiteResp())

/** 获取子大肚腩秋千+团建架构imgrouid */
export const whiteList = () => Mock.mock(ApiResponseListDaDuNanXinXiWhiteResp())
